# Generated by Django 5.0.1 on 2024-01-31 01:49

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('file', models.FileField(upload_to='reports')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Track_Symptom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('severity', models.IntegerField(choices=[(0, 'None'), (1, 'A Little'), (2, 'Quite A Lot'), (3, 'Extreme')], default=0)),
                ('mood', models.IntegerField(choices=[(0, 'Upset'), (1, 'Sad'), (2, 'Anxious'), (3, 'Scared'), (4, 'Confused'), (5, 'Unsure'), (6, 'Calm'), (7, 'Happy')])),
                ('duration', models.IntegerField()),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('notes', models.TextField()),
                ('symptom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meno_tracker.symptom')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Symptom_Treatment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('symptom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meno_tracker.symptom')),
                ('treatment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meno_tracker.treatment')),
            ],
        ),
    ]
