# Generated by Django 5.0.1 on 2024-03-02 16:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meno_tracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('birthdate', models.DateField()),
                ('menopause', models.BooleanField(default=False)),
                ('last_period', models.DateField()),
                ('daily_reminders', models.BooleanField(default=False)),
                ('current_treatments', models.TextField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BaseSymptoms',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('starting_date', models.DateField()),
                ('severity', models.IntegerField(choices=[(0, 'None'), (1, 'A Little'), (2, 'Quite A Lot'), (3, 'Extreme')], default=0)),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meno_tracker.symptom')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meno_tracker.profile')),
            ],
        ),
    ]
