# Generated by Django 5.0.1 on 2024-03-03 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meno_tracker', '0004_profile_basesymptoms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basesymptoms',
            old_name='profile',
            new_name='profile_id',
        ),
        migrations.RenameField(
            model_name='basesymptoms',
            old_name='symptom',
            new_name='symptom_id',
        ),
    ]
